export const RequestRewardStaffModel = {
  StaffID: '',
  ProgramCode: '',
  ProcessCode: '',
  RequestRewardID: '',
  StaffCode: '',
  TitleName: '',
  FirstName: '',
  LastName: '',
  PositionCode: '',
  PositionName: '',
  PosLevel: '',
  PosLevelName: '',
  DepartmentCode: '',
  DepartmentName: '',
  DepartmentLevel: '',
  OfficeCode: '',
  OfficeName: '',
  OfficeShortName: '',
  ContributorID: '',
  IsActive: '',
  FirstMoney: '',
  SecondMoney: '',
  ToTalMoney: '',
  DateReceiveMoney: '',
  FirstPart: '',
  SecondPart: '',
  ContributorName: '',
}

