export const RequestRewardinsAllModel = {
  RequestRewardID: '',
  RequestBribeRewardID: '',
  RequestRewardCode: '',
  FineType: '',
  RequestDate: '',
  RequestTime: '',
  StationCode: '',
  Station: '',
  FirstPartTotal: '',
  FirstMoneyTotal: '',
  FirstMoneyPerPart: '',
  FirstRemainder: '',
  SecondPartTotal: '',
  SecondMoneyTotal: '',
  SecondMoneyPerPart: '',
  SecondRemainder: '',
  RewardTotal: '',
  BribeTotal: '',
  IsActive: '',
  ReferenceNo: '',
  RequestRewardDetail: [],
  RequestRewardStaff: []
};
