export const RequestBribeupdByConModel = {
  RequestBribeID: '',
  RequestBribeRewardID: '',
  RequestBribeCode: '',
  CommandDetailID: '',
  RequestDate: '',
  RequestTime: '',
  StationCode: '',
  Station: '',
  BribeTotal: '',
  BribeRemainder: '',
  Informeracknowledge: '',
  StationOfPOA: '',
  POADate: '',
  POATime: '',
  POANo: '',
  StationCodeOfPOA: '',
  IsActive: '',
  RequestBribeStaff: []
};
